config/routes.rb
Byagustore::Application.routes.draw do
  

  resources :addresses do
    member do
        put :select_address
      end
  end

  

  devise_for :users

  resources :users

  resources :orders do
    member do
      get :checkout
    end
  end
  
   resources :transactions
  resources :line_items
  

  resources :carts
  resources :merchants do
     member do
        put :follow_this_store
        put :unfollow_this_store
      end
  end
  
  

  resources :products do
    resources :photos
  end
  
  resources :category , :only => [:index,:show]

  resources :payments, :only => :new
   match "/line_items/:id" => "line_items#update"
   match "carts/:id" => "carts#show"
   match "/orders/:order_id/transactions/new" => "transactions#new" ,:as => :transactions
  get "home/index"

   root :to => 'home#index'

end

app/models/merchant.rb
# == Schema Information
#
# Table name: merchants
#
#  id                :integer          not null, primary key
#  merchant_name     :string(50)
#  first_name        :string(25)
#  last_name         :string(25)
#  email             :string(25)
#  address           :string(55)
#  city              :string(25)
#  state             :string(3)
#  primary_phone     :string(14)       not null
#  secondary_phone   :string(14)
#  active            :string(1)        default("N")
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  zip               :integer
#  logo_file_name    :string(25)
#  logo_content_type :string(25)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#

class Merchant < ActiveRecord::Base
  has_many :products,:dependent => :destroy
  has_attached_file :logo, :styles => { :thumb => "150x150#", 
    :medium => "300x300#", 
    :large => "500x500>" },
  :url  => "/assets/merchants/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/merchants/:id/:style/:basename.:extension"
    
    attr_accessible :merchant_name,:first_name,:last_name,:email,:address,:city,:state,:zip,
    :primary_phone,:secondary_phone,:logo
    
validates_attachment_presence :logo
#validates_attachment_size :data, :less_than => 5.megabytes
validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png']

validates :merchant_name,:first_name,:last_name,:email,:address,:city,:state,:zip,:primary_phone,:logo, :presence => true

    


  

 
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:new,:show, :index]
  def new
  
    @merchant = Merchant.new(params[:merchant])

    respond_to do |format|
      if @merchant.save
        format.html { render action: "confirm", notice: 'Merchant was successfully created.' }
        format.json { render json: @merchant, status: :created, location: @merchant }
      else
        format.html { render action: "new" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
 
 end
  
  def create
    
    @merchant = Merchant.new(params[:merchant])

    respond_to do |format|
      if @merchant.save
        format.html { render action: "confirm", notice: 'Merchant was successfully created.' }
        format.json { render json: @merchant, status: :created, location: @merchant }
      else
        format.html { render action: "new" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  
  def edit
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      if @merchant.update_attributes(params[:merchant])
        format.html { render "confirm", notice: 'Merchant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
    end
    
    def show
      @merchant = Merchant.find(params[:id])
      @product = Product.find_all_by_merchant_id(@merchant.id)
      
    end
  
    def index
      @merchant = Merchant.all
    end
    
    def follow_this_store
      @merchant = Merchant.find(params[:id])
      merchant_follower =MerchantFollower.new(:merchant_id=> @merchant.id,:user_id => current_user.id,:status=> 'Y')
      merchant_follower.save
     redirect_to merchant_path(@merchant.id)
   end
   
   def unfollow_this_store
     @merchant = Merchant.find(params[:id])
     @merchant_unfollow = MerchantFollower.find_by_merchant_id_and_user_id(@merchant.id,current_user.id)
     @merchant_unfollow.destroy
     redirect_to merchant_path(@merchant.id)
   end
    
    
 
end

app/helpers/merchant_helper.rb
module MerchantHelper
end

app/views/merchants/_form.html.erb
	
	<hr class="soft"/>
	
		<div class="span9">
<%= form_for @merchant, html: { :multipart => true,:class=> "form-horizontal" } do |f| %>
<div  class="alert-error">
<%= render "shared/error_messages", :target => @merchant %>
			<%= flash[:error] %>
			</div>
      <div class="well">
      <div class="control-group">
    <%= f.label :merchant_name,"Store Name*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :merchant_name %>
    </div>
    </div>
  </div>
  
        <div class="control-group">
    <%= f.label :first_name,"First Name*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :first_name %>
    </div>
    </div>
  </div>


      <div class="control-group">
    <%= f.label :last_name,"Last Name*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :last_name %>
    </div>
    </div>
  </div>
  
      <div class="control-group">
    <%= f.label :email,"Email*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :email %>
    </div>
    </div>
  </div>

   
  
     <div class="control-group">
    <%= f.label :address,"Address*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :address %>
    </div>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :city,"City*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :city %>
    </div>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :state,"State*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :state %>
    </div>
    </div>
  </div>
  
   <div class="control-group">
    <%= f.label :zip,"zip*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :zip %>
    </div>
    </div>
  </div>
  
   <div class="control-group">
    <%= f.label :primary_phone,"Primary Phone*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :primary_phone %>
    </div>
    </div>
  </div>
  
    <div class="control-group">
    <%= f.label :secondary_phone,"Secondary Phone*", :class=>"control-label" %>
    <div class="controls">
    	
    	<div id="inputFname1">
    	
    <%= f.text_field :secondary_phone %>
    </div>
    </div>
  </div>
  
    <div class="control-group">
    	 <%= f.label :logo,"Upload Logo/Pic*", :class=>"control-label" %>
    	 <div class="controls">
    	<div id="inputFname1">
    	<%= f.file_field :logo %>
    </div>
    </div>
    </div>
 

<div class="control-group">
	  	<div class="controls">
	  		
    <%= f.submit "Submit", :class=>"btn btn-success btn-large" %>
    </div>
  </div>
   </div>
  <% end %>

  
   

app/views/merchants/confirm.html.erb
Thank you for signing up . Once of our sale rep will get in touch with you for bringing you aboard
<%= link_to 'Edit' , edit_merchant_path('3')%>

app/views/merchants/edit.html.erb
<div class="span9">
    <ul class="breadcrumb">
		<li><a href="index.html">Home</a> <span class="divider">/</span></li>
		<li><a href="index.html">Products</a> <span class="divider">/</span></li>
		<li class="active">Merchant Sign up </li>
    </ul>
	<h3> Edit Merchant </h3>	
<%= render 'form' %>

  </div>

app/views/merchants/index.html.erb
<div id="mainBody">
  <div class="container">
  <div class="row">
  
  
  <div class="span9">
    <ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li><a href="products.html">Products</a> <span class="divider">/</span></li>
    <li class="active">Stores</li>
    </ul>	
	<ul class="thumbnails"> 
			
<% @merchant.each do |f| %>
<li class="span3">
	<div class="thumbnail">
<%= link_to image_tag(f.logo.url(:thumb), :style=>"width:30%"), merchant_path(f.id) %>
 <div class="caption">
<h5><%= link_to f.merchant_name.titleize , merchant_path(f.id) %></h5>
<p class="bar-info">
<%= f.city.capitalize %>,
<%= f.state.upcase %>
</p>

</div>
          </div>
        </li>
<% end %>
 </ul> 
      </div>
    </div>
    </div>
  </div>
</div>

app/views/merchants/new.html.erb
<div class="span9">
    <ul class="breadcrumb">
		<li><a href="index.html">Home</a> <span class="divider">/</span></li>
		<li><a href="index.html">Products</a> <span class="divider">/</span></li>
		<li class="active">Merchant Sign up </li>
    </ul>
	<h3> Merchant Sign up </h3>	
<%= render 'form' %>

  </div>

app/views/merchants/show.html.erb
<div id="mainBody">
  <div class="container">
  <div class="row">
  
  
  <div class="span9">
    <ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li><a href="products.html">Products</a> <span class="divider">/</span></li>
    <li class="active">Stores</li>
    </ul>	
	

<div class="well">
	<%= image_tag(@merchant.logo.url(:thumb), :style => "width:20%")%>
	
	<div class="bar-info pull-right">
		<div class="caption">
<h3><%= @merchant.merchant_name.titleize %></h3>
</div>
<h5><%= @merchant.address.titleize %><br>
<%= @merchant.city.titleize %>,
<%= @merchant.state.upcase %>
<%= @merchant.zip %><br><%= @merchant.primary_phone %>

</h5>

<% if !current_user.nil?%>
<% if MerchantFollower.following(@merchant.id,current_user.id) > 0%>
<%= button_to  "Unfollow", unfollow_this_store_merchant_path(@merchant.id),:class=>"btn btn-large btn-success" ,:method => :put%>

<% else %>
<%= button_to  "Follow Store", follow_this_store_merchant_path(@merchant.id),:class=>"btn btn-large btn-success" ,:method => :put%>
<% end %>
<% else %>
<%= button_to  "Follow Store", follow_this_store_merchant_path(@merchant.id),:class=>"btn btn-large btn-success" ,:method => :put%>
<% end %>
</div>

</div>


<ul class="thumbnails">
        	<% @product.each do |product| %>
        <li class="span3">
          <div class="thumbnail">
          	<% product.photos.each_with_index do |photo, i| %>
          	<% if i == 0%>
         
          <%= link_to (image_tag photo.data.url(:thumb)), product_path(product.id) %>
            <% end %>
            <% end %>
          <div class="caption">
            <h5><%= product.name %></h5>
            <p> 
           
            
            	<h4><%= link_to "View", product_path(product.id) ,:class => "btn btn-medium" %>
            
            	 <span class="pull-right">$<%= product.price %></span></h4>
          </div>
          </div>
        </li>
        <% end %>
        </ul> 

</div>
</div>