config/routes.rb
Byagustore::Application.routes.draw do
  

  resources :addresses do
    member do
        put :select_address
      end
  end

  

  devise_for :users

  resources :users

  resources :orders do
    member do
      get :checkout
    end
  end
  
   resources :transactions
  resources :line_items
  

  resources :carts
  resources :merchants do
     member do
        put :follow_this_store
        put :unfollow_this_store
      end
  end
  
  

  resources :products do
    resources :photos
  end
  
  resources :category , :only => [:index,:show]

  resources :payments, :only => :new
   match "/line_items/:id" => "line_items#update"
   match "carts/:id" => "carts#show"
   match "/orders/:order_id/transactions/new" => "transactions#new" ,:as => :transactions
  get "home/index"

   root :to => 'home#index'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id           :integer          not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  purchased_at :datetime
#

class Cart < ActiveRecord::Base
   attr_accessible :purchased_at
  has_many :line_items, dependent: :destroy
  has_one :order

  def add_product(product_id,qty=1)
  	current_item = line_items.find_by_product_id(product_id)
    	if current_item 
  		current_item.quantity += qty
  	else
  		current_item = line_items.build(product_id: product_id, quantity: qty)
  	end
  
	current_item  	
  end

 def self.get_total(current_cart)
  @cart = Cart.find(current_cart)
  @lineitem = @cart.line_items
    @total = 0
    for item in @lineitem
      @price = item.product.price * item.quantity
      @total = @total + @price
    end
    @total
  end
  
  def total_price
    line_items.to_a.sum(&:full_price)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 
  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = current_cart
    @lineitem = @cart.line_items
     @category_div = Category.get_category
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
	
end

app/views/carts/Copy of _line_item.erb
<%  @lineitem.each do |item| %>

<tr>
	<td><%= item.id %>
<td><%= item.product.name %></td>
<td><%= number_to_currency(item.product.price) %></td>

<td><%= form_for(item) do |f| %>
 

  <div class="field">

    <%= f.number_field  :quantity %>
    <%= f.submit "update" %>
  </div>
<% end %>
</td>
<td><%= number_to_currency(LineItem.get_price(item.id,item.product.price)) %></td>

<td><%= link_to 'Remove', item , confirm: 'Are you sure?', method: :delete  %></td>

</tr>

<% end %>

app/views/carts/Copy of show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'home/category_sidebar'%>
<span> <%= link_to 'Check Out',new_payment_path %></span>
<table>
	<tr>
		<th> ID </th>
		<th>Name </th>
		<th>Unit Price </th>
		<th> Quantity </th>
		<th>  Price </th>
		<th></th>
	</tr>

<%= render :partial => 'line_item' %>

</table>
<span> Total </span><%=  number_to_currency(Cart.get_total(session[:cart_id]))%>


	

app/views/carts/_edit_cart.html.erb
<%= form_for(@lineitem)

app/views/carts/_form.html.erb
<%= form_for(@cart.line_items) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field f.quantity %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/_line_item.erb
<%  @lineitem.each do |item| %>

<tr>
	<td><%= item.id %>
<td><%= item.product.name %></td>
<td><%= number_to_currency(item.product.price) %></td>

<td><%= form_for(item) do |f| %>
 

  <div class="field">

    <%= f.number_field  :quantity %>
    <%= f.submit "update" %>
  </div>
<% end %>
</td>
<td><%= number_to_currency(LineItem.get_price(item.id,item.product.price)) %></td>

<td><%= link_to 'Remove', item , confirm: 'Are you sure?', method: :delete  %></td>

</tr>

<% end %>

app/views/carts/_show.html.erb
<table class="table table-bordered">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Description</th>
                  <th>Quantity/Update</th>
				  <th>Price</th>
                  <th>Discount</th>
                  <th>Tax</th>
                  <th>Total</th>
				</tr>
              </thead>
              <tbody>
              	<%  @lineitem.each do |item| %>
                <tr>
             

                  <td> 
                  	<% item.product.photos.each_with_index do |photo, i| %>
          	<% if i == 0%>
         
         <%= link_to (image_tag photo.data.url(:thumb), :width => 60), product_path(item.product.id) %>
            <% end %>
            <% end %>
                  </td>
                  <td><b><%= link_to item.product.name,product_path(item.product.id) %></b>
                  	<% if !item.variant_value.nil? %><br/>
                  	<%= item.variant  %>:
                  	<%= item.variant_value %>
                  	<% end %>
				  <td>
				  	
					<div class="input-append">
						<%= form_for(item) do |f| %>
						<%= f.number_field  :quantity ,:class=> 'span1', :style=>"max-width:34px"%>
						
						<%= f.submit "Update" , :class=>"btn"%>
						
						<% end %>
						
						<%= link_to "Remove", item , confirm: 'Are you sure?', method: :delete ,:class=>"btn btn-danger" %>	
													
						</div>
						
				  </td>
				 
                  <td><%= number_to_currency(item.product.price) %></td>
                  <td>0</td>
                   <td>0</td>
                    <td><%= number_to_currency(item.product.price * item.quantity)  %></td>
   
                </tr>
				
				<%end %>
                <tr>
                  <td colspan="6" style="text-align:right">Total Price:	</td>
                  <td> <%=  number_to_currency(Cart.get_total(current_cart))%></td>
                </tr>
				 <tr>
                  <td colspan="6" style="text-align:right">Total Discount:	</td>
                  <td> $0.00</td>
                </tr>
                 <tr>
                  <td colspan="6" style="text-align:right">Total Tax:	</td>
                  <td> $0.00</td>
                </tr>
				 <tr>
                  <td colspan="6" style="text-align:right"><strong>TOTAL =</strong></td>
                  <td class="label label-important"> <strong> <%=  number_to_currency(Cart.get_total(current_cart))%> </strong></td>
                </tr>
				</tbody>
            </table>
		
		
            <table class="table table-bordered">
			<tbody>
				 <tr>
                  <td> 
				<form class="form-horizontal">
				<div class="control-group">
				<label class="control-label"><strong> VOUCHERS CODE: </strong> </label>
				<div class="controls">
				<input type="text" class="input-medium" placeholder="CODE">
				<button type="submit" class="btn"> ADD </button>
				</div>
				</div>
				</form>
				</td>
                </tr>
				
			</tbody>
			</table>
				<%= link_to products_path, :class=>"btn btn-large"  do %>
				<i class="icon-arrow-left"></i> Continue Shopping 
				<% end %>
				
	
	<%= link_to new_address_path , :class=>"btn btn-large pull-right" do  %>
	Check Out<i class="icon-arrow-right"></i> 
	<% end %>
	

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'home/category_sidebar'%>

	<div class="span9">
    <ul class="breadcrumb">
		<li><%= link_to "Home" , root_path %> <span class="divider">/</span></li>
		<li class="active"> SHOPPING CART</li>
    </ul>
	<h3>  SHOPPING CART [ <small><%= LineItem.get_count(current_cart) %> Item(s) </small>]	
		
		<%= link_to products_path , :class=>"btn btn-large pull-right" do %>
		<i class="icon-arrow-left"></i> <span style="font-weight:normal;">Continue Shopping </span>
		<% end %>
		</h3>
	<hr class="soft"/>
	

<table class="table table-bordered">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Description</th>
                  <th>Quantity/Update</th>
				  <th>Price</th>
                  <th>Discount</th>
                  <th>Tax</th>
                  <th>Total</th>
				</tr>
              </thead>
              <tbody>
              	<%  @lineitem.each do |item| %>
                <tr>
             

                  <td> 
                  	<% item.product.photos.each_with_index do |photo, i| %>
          	<% if i == 0%>
         
         <%= link_to (image_tag photo.data.url(:thumb), :width => 60), product_path(item.product.id) %>
            <% end %>
            <% end %>
                  </td>
                  <td><b><%= link_to item.product.name,product_path(item.product.id) %></b>
                  	<% if !item.variant_value.nil? %><br/>
                  	<%= item.variant  %>:
                  	<%= item.variant_value %>
                  	<% end %>
				  <td>
				  	
					<div class="input-append">
						<%= form_for(item) do |f| %>
						<%= f.number_field  :quantity ,:class=> 'span1', :style=>"max-width:34px"%>
						
						<%= f.submit "Update" , :class=>"btn"%>
						
						<% end %>
						
						<%= link_to "Remove", item , confirm: 'Are you sure?', method: :delete ,:class=>"btn btn-danger" %>	
													
						</div>
						
				  </td>
				 
                  <td><%= number_to_currency(item.product.price) %></td>
                  <td>0</td>
                   <td>0</td>
                    <td><%= number_to_currency(item.product.price * item.quantity)  %></td>
   
                </tr>
				
				<%end %>
                <tr>
                  <td colspan="6" style="text-align:right">Total Price:	</td>
                  <td> <%=  number_to_currency(Cart.get_total(current_cart))%></td>
                </tr>
				 <tr>
                  <td colspan="6" style="text-align:right">Total Discount:	</td>
                  <td> $0.00</td>
                </tr>
                 <tr>
                  <td colspan="6" style="text-align:right">Total Tax:	</td>
                  <td> $0.00</td>
                </tr>
				 <tr>
                  <td colspan="6" style="text-align:right"><strong>TOTAL =</strong></td>
                  <td class="label label-important"> <strong> <%=  number_to_currency(Cart.get_total(current_cart))%> </strong></td>
                </tr>
				</tbody>
            </table>
		
		
				<%= link_to products_path, :class=>"btn btn-large"  do %>
				<i class="icon-arrow-left"></i> Continue Shopping 
				<% end %>
				
	<% if Cart.get_total(current_cart) > 0 %>
	<%= link_to address_path(current_user) , :class=>"btn btn-large pull-right" do  %>
	Check Out<i class="icon-arrow-right"></i> 
	<% end %>
	<% end %>
	
		






	