config/routes.rb
Byagustore::Application.routes.draw do
  

  resources :addresses do
    member do
        put :select_address
      end
  end

  

  devise_for :users

  resources :users

  resources :orders do
    member do
      get :checkout
    end
  end
  
   resources :transactions
  resources :line_items
  

  resources :carts
  resources :merchants do
     member do
        put :follow_this_store
        put :unfollow_this_store
      end
  end
  
  

  resources :products do
    resources :photos
  end
  
  resources :category , :only => [:index,:show]

  resources :payments, :only => :new
   match "/line_items/:id" => "line_items#update"
   match "carts/:id" => "carts#show"
   match "/orders/:order_id/transactions/new" => "transactions#new" ,:as => :transactions
  get "home/index"

   root :to => 'home#index'

end

app/views/layouts/_banner.html.erb
<div id="carouselBlk">
<div class="container">
  <div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="item active">
      <%= link_to image_tag("/themes/images/carousel/1.png", :style=>"width:100%" ), products_path %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
      <div class="item">
      <%= link_to image_tag("/themes/images/carousel/2.png", :style=>"width:100%" ), products_path %>
        <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
      <div class="item">
       <%= link_to image_tag("/themes/images/carousel/3.png", :style=>"width:100%" ), products_path %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      
      </div>
       <div class="item">
       <%= link_to image_tag("/themes/images/carousel/4.png", :style=>"width:100%" ), products_path %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
       
      </div>
       <div class="item">
       <%= link_to image_tag("/themes/images/carousel/5.png", :style=>"width:100%" ), products_path %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
  <!--<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a> -->
    </div> 
</div>
</div>

app/views/layouts/_featured_products.html.erb
<div class="span12">
    <div>
      <h3>Featured Products </h3>
      <div class="row-fluid">
      <div id="featured" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
        	 
        <ul class="thumbnails">
        <% @featured.each do |product| %>
        <li class="span3">
          <div class="thumbnail">
          	<% product.photos.each_with_index do |photo, i| %>
          	<% if i == 0%>
         
          <%= link_to (image_tag photo.data.url(:medium),:width=>200), product_path(product.id) %>
            <% end %>
            <% end %>
            <div class="caption">
            	<h5><%= product.name.titleize %></h5>
            	<h5><%= link_to "View", product_path(product.id) ,:class => " btn btn-medium " %>
            		<span class="pull-right">$<%= product.price %>
            	</h5>
            	 </div>
          </div>
          <% end %>
        </li>
   </ul>
   </div>
    <div class="item">
        	 
        <ul class="thumbnails">
        <% @featured.each do |product| %>
        <li class="span3">
          <div class="thumbnail">
          	<% product.photos.each_with_index do |photo, i| %>
          	<% if i == 0%>
         
          <%= link_to (image_tag photo.data.url(:medium),:width=>200), product_path(product.id) %>
            <% end %>
            <% end %>
            <div class="caption">
            	<h5><%= product.name.titleize %></h5>
            	<h5><%= link_to "View", product_path(product.id) ,:class => "btn btn-medium" %>
            		<span class="pull-right">$<%= product.price %>
            	</h5>
            	 </div>
          </div>
          <% end %>
        </li>
   </ul>
   
   </div>
   
   
   </div>
    <a class="left carousel-control" href="#featured" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#featured" data-slide="next">&rsaquo;</a>
        </div>
        </div>

app/views/layouts/_footer.html.erb
<!-- Footer ================================================================== -->
	<hr class="soft">
	<div  id="footerSection">
	<div class="container">
		<div class="row">
			<div class="span3">
				<h5>ACCOUNT</h5>
				<a href="login.html">YOUR ACCOUNT</a>
				<a href="login.html">PERSONAL INFORMATION</a> 
				<a href="login.html">ADDRESSES</a> 
				<a href="login.html">DISCOUNT</a>  
				<a href="login.html">ORDER HISTORY</a>
			 </div>
			<div class="span3">
				<h5>INFORMATION</h5>
				<a href="contact.html">CONTACT</a>  
				<a href="register.html">REGISTRATION</a>  
				<%= link_to "STORE SIGN UP" , new_merchant_path %> 
				<a href="legal_notice.html">LEGAL NOTICE</a>  
				<a href="tac.html">TERMS AND CONDITIONS</a> 
				<a href="faq.html">FAQ</a>
			 </div>
			<div class="span3">
				<h5>OUR OFFERS</h5>
				<a href="#">NEW PRODUCTS</a> 
				<%= link_to "OUR STORES", merchants_path %>  
				<a href="special_offer.html">SPECIAL OFFERS</a>  
				<%= link_to "SUPPLIERS", merchants_path %>  
			 </div>
			<div id="socialMedia" class="span3 pull-right">
				<h5>SOCIAL MEDIA </h5>
				<a href="#"><img width="60" height="60" src="/themes/images/facebook.png" title="facebook" alt="facebook"/></a>
				<a href="#"><img width="60" height="60" src="/themes/images/twitter.png" title="twitter" alt="twitter"/></a>
				<a href="#"><img width="60" height="60" src="/themes/images/rss.png" title="rss" alt="rss"/></a>
				<a href="#"><img width="60" height="60" src="/themes/images/youtube.png" title="youtube" alt="youtube"/></a>
			 </div> 
		 </div>
		 <hr class="soft">
	
	</div><!-- Container End -->
	</div>

app/views/layouts/_header.html.erb
<div id="header">
<div class="container">
<div id="welcomeLine" class="row">
  <div class="span6"><% if user_signed_in? %> <span class="pull-left"> <b>Namaste!!</b> &nbsp;<span style="color:green; font-weight:bold "><%=  current_user.email %> </span>
  	<% else%> <b>Welcome!! </b><% end %></div>
  <div class="span6">
  <div class="pull-right">
  	
  <% if  !current_cart.nil? %>
  <span class="btn btn-mini">$<%= Cart.get_total(current_cart)%></span>
  <%= link_to cart_path(current_cart), :data=>{:toggle => "popover", :content=>"#{render 'shared/main_cart'}"},:id=>"maincart" do %>
  <span class="btn btn-mini active">
  <i class="icon-shopping-cart icon-white">
  </i> [<%= LineItem.get_count(current_cart) %>] Items in your cart  </span>
  <% end %>
   <% end %>
  
  </div>

		

  
  </div>
</div>
<!-- Navbar ================================================== -->
<div id="logoArea" class="navbar">
<a data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
 
<div class="navbar-inner">
    <%= link_to (image_tag("/themes/images/byagu2.png",:class=>"brand")) ,root_path %>
    

   
    <ul id="topMenu" class="nav pull-right">
     <li class=""><%= link_to "Specials Offer" , products_path %></a></li>
   <li class=""><a href="contact.html">Contact</a></li>
   <li class=""><a href="#">My Account</a></li>
   <li class="">
   	<% if !user_signed_in? %>
 <span class="btn">
    <%= link_to "Sign In!!", new_user_session_path, :class=>"dropdown-toggle" %>
    
   </span>
    
    <% else%>
   <%= link_to "Sign Out!!", destroy_user_session_path, :method => :delete  %>
   
    <%end %> 

  </li>
    </ul>
<form action="#" class="navbar-search">
	 <input id="srchFld" type="text" placeholder="I'm looking for ..." class="search-query span5"/>
	</form>
  </div>
</div>
</div>
</div>

app/views/layouts/_main_body.html.erb
 <h3>Latest Products </h3>

        <ul class="thumbnails">
        	<% @product.each do |product| %>
       <li class="span3">
          <div class="thumbnail">
          	<% product.photos.each_with_index do |photo, i| %>
          	<% if i == 0%>
         
          <%= link_to (image_tag photo.data.url(:medium),:width=>200), product_path(product.id) %>
            <% end %>
            <% end %>
            <div class="caption">
            	<h5><%= product.name.titleize %></h5>
            	<h5><%= link_to "View", product_path(product.id) ,:class => " btn btn-medium " %>
            		<span class="pull-right">$<%= product.price %>
            	</h5>
            	 </div>
          </div>
          <% end %>
        </li>
   </ul>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/layouts/_sample_products.html.erb
    <div class="span9">
    <div>
      <h3>Featured Products </h3>
      <div class="row-fluid">
      <div id="featured" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
        <ul class="thumbnails">
        <li class="span3">
          <div class="thumbnail">
          <i class="tag"></i>
          <a  href="product_details.html"><img src="../themes/images/products/1.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <i class="tag"></i>
          <a  href="product_details.html"><img src="../themes/images/products/2.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <i class="tag"></i>
          <a  href="product_details.html"><img src="../themes/images/products/3.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <i class="tag"></i>
          <a  href="product_details.html"><img src="../themes/images/products/4.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        </ul>
        </div>
         <div class="item">
        <ul class="thumbnails">
        <li class="span3">
          <div class="thumbnail">
          <i class="tag"></i>
          <a  href="product_details.html"><img src="../themes/images/products/5.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <i class="tag"></i>
          <a  href="product_details.html"><img src="../themes/images/products/6.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/7.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/8.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        </ul>
        </div>
         <div class="item">
        <ul class="thumbnails">
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/9.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/10.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/11.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/1.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        </ul>
        </div>
         <div class="item">
        <ul class="thumbnails">
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/2.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/3.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
            <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/4.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        <li class="span3">
          <div class="thumbnail">
          <a  href="product_details.html"><img src="../themes/images/products/5.jpg" alt=""/></a>
          <div class="caption">
            <h5>Product name</h5>
             <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
          </div>
          </div>
        </li>
        </ul>
        </div>
        </div>
        <a class="left carousel-control" href="#featured" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#featured" data-slide="next">&rsaquo;</a>
        </div>
        </div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="span3">
    <div class="navbar">
      <a data-target="#sideManu" data-toggle="collapse" class="btn btn-navbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </a>
    </div>
    
<ul id="sideManu" class="nav nav-tabs nav-stacked">
      <li>
        <% if  !session[:cart_id].nil? %>
        <%= link_to cart_path(session[:cart_id]) do %>
      <img src="../themes/images/ico-cart.png" alt="cart" />
      <b><%= LineItem.get_count(session[:cart_id]) %>  Items in your cart </b>
      <span class="badge badge-warning pull-right">$0.00</span>
      <% end %>
      <% end %></li>
      <li class="subMenu open"><a> ELECTRONICS [230]</a>
        <ul>
        <li><a class="active" href="products.html">Cameras (100)</a></li>
        <li><a href="products.html">Computers, Tablets & laptop (30)</a></li>
        <li><a href="products.html">Mobile Phone (80)</a></li>
        <li><a href="products.html">Sound & Vision (15)</a></li>
        </ul>
      </li>
      <li class="subMenu"><a> CLOTHES [840] </a>
      <ul style="display:none">
        <li><a href="products.html">Women's Clothing (45)</a></li>
        <li><a href="products.html">Women's Shoes (8)</a></li>                        
        <li><a href="products.html">Women's Hand Bags (5)</a></li>  
        <li><a href="products.html">Men's Clothings  (45)</a></li>
        <li><a href="products.html">Men's Shoes (6)</a></li>                        
        <li><a href="products.html">Kids Clothing (5)</a></li>                        
        <li><a href="products.html">Kids Shoes (3)</a></li>                       
      </ul>
      </li>
      <li class="subMenu"><a>FOOD AND BEVERAGES [1000]</a>
        <ul style="display:none">
        <li><a href="products.html">Angoves  (35)</a></li>
        <li><a href="products.html">Bouchard Aine & Fils (8)</a></li>                       
        <li><a href="products.html">French Rabbit (5)</a></li>  
        <li><a href="products.html">Louis Bernard  (45)</a></li>
        <li><a href="products.html">BIB Wine (Bag in Box) (8)</a></li>                        
        <li><a href="products.html">Other Liquors & Wine (5)</a></li>                       
        <li><a href="products.html">Garden (3)</a></li>                       
        <li><a href="products.html">Khao Shong (11)</a></li>                        
      </ul>
      </li>
      <li><a href="products.html">HEALTH & BEAUTY [18]</a></li>
      <li><a href="products.html">SPORTS & LEISURE [58]</a></li>
      <li><a href="products.html">BOOKS & ENTERTAINMENTS [14]</a></li>
      <li style="border:0"> &nbsp;</li>           
      
      <li style="border:0"> &nbsp;</li> 
      <li>
        <div class="thumbnail">
        <img src="../themes/images/products/panasonic.jpg" alt="Bootshop panasonoc New camera"/>
        <div class="caption">
          <h5>Panasonic</h5>
          <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
        </div>
        </div>
      </li>
      <li style="border:0"> &nbsp;</li>   
      <li>
      <div class="thumbnail">
        <img src="../themes/images/products/kindle.png" title="Bootshop New Kindel" alt="Bootshop Kindel">
        <div class="caption">
          <h5>Kindle</h5>
          <h4><a class="btn" href="product_details.html">VIEW</a> <span class="pull-right">$222.00</span></h4>
        </div>
        </div>
      </li> 
      <li class="last">
      <div class="thumbnail">
        <img src="../themes/images/payment_methods.png" title="Bootshop Payment Methods" alt="Payments Methods">
        <div class="caption">
          <h5>Payment Methods</h5>
        </div>
        </div>
      </li> 
      </ul>
  </div>
  

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag 'bootstrap/css/bootstrap.css', :media=>'screen' %>
   <%= stylesheet_link_tag 'bootstrap/css/bootstrap-responsive.css', :media=>'screen' %>
    <!--[if lt 8]><%=stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  

    <!--Less styles -->
   <!-- Other Less css file //different less files has different color scheam
	<%= stylesheet_link_tag 'themes/less/simplex.less', :media=>'screen' %>
	<%= stylesheet_link_tag "themes/less/classified.less", :media=>'screen' %>
	<%= stylesheet_link_tag"themes/less/amelia.less" , :media=>'screen' %> MOVE DOWN TO activate
	
	<%= stylesheet_link_tag"themes/less/bootshop.less",  :media=>'screen' %>
	<script src="themes/js/less.js" type="text/javascript"></script> -->
	
<!-- Bootstrap style  
	--> 
    <%= stylesheet_link_tag "themes/css/bootstrap.min.css" , :media=>'screen' %>
	<%= stylesheet_link_tag "themes/css/style.css" , :media=>'screen' %>
<!-- customized css
	-->
<!-- Bootstrap style responsive 
	-->	
	<%= stylesheet_link_tag "themes/css/bootstrap-responsive.min.css" , :media=>'screen' %>
<!-- Google-code-prettify -->	
	<%= stylesheet_link_tag "themes/js/google-code-prettify/prettify.css" , :media=>'screen' %>
<!-- fav and touch icons -->
    
   
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Byagu your store our service</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  <%= render 'layouts/stylesheets'%>
  <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Patua+One'>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="/themes/js/less.js" type="text/javascript"></script> 
     
  <%= javascript_include_tag "application" %>
   <%= javascript_include_tag "Braintree" %>
   
  <link rel="shortcut icon" href="/themes/images/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/themes/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/themes/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/themes/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/themes/images/ico/apple-touch-icon-57-precomposed.png">
  
 
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>
<%= render 'layouts/footer' %>



</div>

<!-- Placed at the end of the document so the pages load faster ============================================= -->
   <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
	
	<script src="/themes/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="/themes/js/google-code-prettify/prettify.js"></script>
	<script src="/themes/js/bootshop.js"></script>
	
    
     <%= javascript_include_tag "jquery.lightbox-0.5" %>
	<script type="text/javascript">
	$('#myCarousel').carousel({
	  interval: 8000
	})
	 $('#featured').carousel({
	  interval: 4000
	})
	$('#differentview').carousel({
	  interval: 2000
	})
	$(function() {
		$('#gallery a').lightBox();
	});
	
	$(function(){
		$('#maincart').popover({trigger: 'manual' ,
		                       placement: 'bottom',                      
		                        html : true 
		                        }).mouseover(function (e) {
        // when hovering over an element which has a popover, hide
        // them all except the current one being hovered upon
        $('[rel=popover]').not('#' + $(this).attr('id')).popover('hide');
        var $popover = $(this);
        $popover.popover('show');

        // set a flag when you move from button to popover
        // dirty but only way I could think of to prevent
        // closing the popover when you are navigate across
        // the white space between the two
        $popover.data('popover').tip().mouseenter(function () {
            overPopup = true;
        }).mouseleave(function () {
            overPopup = false;
            $popover.popover('hide');
        })}).mouseout(function (e) {
        // on mouse out of button, close the related popover
        // in 200 milliseconds if you're not hovering over the popover
        var $popover = $(this);
        setTimeout(function () {
            if (!overPopup) {
                $popover.popover('hide');
            }
        }, 200);
    });;  
	});
	</script>
</body>
</html>